Repository nathanielmillard/Crate, pull requests merged in 2020-12, with the labels that each got.

#34 Render profile
  code/package-lock.json
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/Profile.js
  pull_request_template.md
Labels: Author needs review, FE, New Feature, UI

#37 Render subscriptions
  code/web/src/modules/subscription/Item.js
  code/web/src/modules/user/EditProfile.js
  code/web/src/modules/user/Profile.js
  code/web/src/setup/store.js
Labels: Chore, Environment Setup, FE, New Feature, UI

#42 Testing
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/pages/tests/Home.test.js
  code/web/src/modules/user/api/state.test.js
  code/web/src/modules/user/tests/Profile.test.js
  code/web/src/modules/user/tests/Subscriptions.test.js
Labels: Documentation, FE, Testing, UI

#43 Add migration to add the 'description' column to users
  code/api/package-lock.json
  code/api/src/migrations/addPersonal.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/tests/userQuery.test.js
  code/api/src/modules/user/types.js
  code/api/src/seeders/1-user.js
  code/api/src/utils/testHelper/testServer.js
Labels: BE

#47 Revert "Add migration to add the 'description' column to users"
  code/api/package-lock.json
  code/api/src/migrations/addPersonal.js
  code/api/src/modules/user/model.js
  code/api/src/modules/user/tests/userQuery.test.js
  code/api/src/modules/user/types.js
  code/api/src/seeders/1-user.js
  code/api/src/utils/testHelper/testServer.js
Labels: Bug

#46 Data mocking
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/EditProfile.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/ui/image/Tile.js
Labels: Author thinks ready to merge, FE, New Feature, UI

#48 Format edit profile
  code/web/src/modules/user/EditProfile.js
  code/web/src/modules/user/Profile.js
Labels: Documentation, FE, UX

#51 Am testing
  code/web/src/modules/pages/tests/Home.test.js
  code/web/src/modules/user/api/state.test.js
  code/web/src/modules/user/tests/Profile.test.js
  code/web/src/modules/user/tests/Subscriptions.test.js
  package-lock.json
Labels: FE, Testing

#52 Format profile
  code/web/src/modules/user/EditProfile.js
  code/web/src/modules/user/Profile.js
Labels: Documentation, FE, Refactor, UX
